name: Build and Deploy nbox
on:
  push:
    branches: [v1]
    paths:
      -"pyproject.toml"
  
  # workflow_dispatch gives a button on the Github UI to run this workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GH_SUBMODULE_TOKEN }}
      
      - name: Install poetry
        run: pipx install poetry==1.2.2
      
      - name: Push
        run: poetry publish --build -u ${{secrets.NBX_PYPI_USERNAME}} -p ${{secrets.NBX_PYPI_PWD}}
